appone/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

app_name = 'appone'

urlpatterns = [
    path('calc/',views.calc,name='calc'),
]

apptwo/urls.py
from django.urls import path
from . import views

app_name = "apptwo"
urlpatterns = [
    path('tnku/',views.tnku,name='tnku'),

]

proj/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

 
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='index'),
    path('appone/',include('appone.urls')),
    path('apptwo/',include('apptwo.urls')),

]

apptwo/models.py
from django.db import models

# Create your models here.

appone/views.py
from django.shortcuts import render

def calc(request):
    c=0
    if request.method == 'POST':
        a = request.POST['num1']
        b = request.POST['num2']
        op = request.POST['op']
        if op not in ['+','-','*','/','%']:
            c = 'SELECT AN OPERAND'
            return render(request,'appone/calc.html',{'error':c})
        else:
            c=result(a,b,op)
    return render(request,'appone/calc.html',{'result':c})

def result(a,b,op):
    return eval(a+op+b)

apptwo/views.py
from django.shortcuts import render

def tnku(request):
    s = "HOPE YOU LIKED IT !"
    return render(request,'apptwo/tnku.html',{'note':s})

proj/views.py
from django.shortcuts import render

def index(request):
    return render(request,'index.html',{})

templates/appone/calc.html
{% extends "base.html" %}

{% block bb %}
    <style>
        body { padding-top: 70px;
             }
        .jumbotron,.container
        {
            background-color:#3253;
            color:#0e0d2e;
            text-align: center;
            margin-top: 5%;
        }
          
        </style>

    <div class='row'>
    <div class="col-sm-6 offset-sm-3 align-items-center col-md-6">
        <div class="form-group container jumbotron">
            <h1>{{result}}</h1>
            <h1>{{error}}</h1>
                <form method='POST'>
                    {% csrf_token %}
                    ENTER NUMBER 1
                    <input class="form-control" type="number" name='num1' placeholder="first number" required>
                    ENTER NUMBER 2
                    <input class="form-control" type="number" name='num2' placeholder="second number" required>
                    <br>
                    <select class="btn btn-info" name='op'>
                        <option>SELECT OPERATION</option>
                        <option>+</option>
                        <option>-</option>
                        <option>*</option>
                        <option>/</option>
                        <option>%</option>
                        <option>**</option>
                        
                    </select>
                    <br><br>
                    <input class="btn btn-success" type="submit" name="SUBMIT">
                </form>
    </div>
    </div>
    </div>  
{% endblock %}

templates/apptwo/tnku.html
{% extends 'base.html' %}
{% block bb %}
        <style>
        body { padding-top: 70px; 
        }
        .jumbotron,.container
        {
            background-color:#3253;
            color:#0e0d2e;
            text-align: center;
            padding-top:15%;
        }
          
        </style>
   <br><br>
   
    <div class="container">
        <div class="jumbotron">
            <h2>{{note}}</h2>
            <h1>THANKYOU FOR VISITING ..!!</h1>
        </div>
    </div>


{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</head>
<body>
    <nav class="navbar navbar-dark bg-dark navbar-expand-sm fixed-top">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">

            <ul class="navbar-nav navbar-brand navbar-brand">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'index' %}">HOME</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'appone:calc' %}">CALCULATOR</a>
                </li>
                <li>
                    <a class="nav-link" href="{% url 'apptwo:tnku' %}">CLICK HERE</a>

                </li>
            </ul>

          </div>
        
    </nav>

    {% block bb %}
    {% endblock %}
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% block bb %}
        <style>
        body { padding-top: 70px; 
        }
        .jumbotron,.container
        {
            background-color:#3253;
            color:#0e0d2e;
            text-align: center;
            padding-top:15%;
        }
          
        </style>
   <br><br>
    <div class="container">
        <div class="jumbotron">
            <h1>WELCOME TO MY CALCULATOR</h1>
        </div>
    </div>


{% endblock %}